trigger:
- master

pool:
  vmImage: 'ubuntu-22.04'

matrix:
  job1:
    ARCH_TAG: foo
  job2:
    ARCH_TAG: bar

steps:

- script: |
    echo "blah blah blah" > test.txt
  displayName: 'create content'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: test.txt
    artifactName: 'libtiledb-$(Agent.OS)$(ARCH_TAG)'
