trigger:
- master

strategy:
  matrix:
    mac:
      imageName: 'vs2017-win2016'
      python.version: '3.x'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'

- script: |
    python -c "import sys; print(sys.executable)"
  displayName: 'script'
- bash: |
    python -c "import sys; print(sys.executable)"
  displayName: 'bash'
- cmd: |
    python -c "import sys; print(sys.executable)"
  displayName: 'cmd'
