trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.x
    addToPath: true
    architecture: x86

- script: |
    python --version
    python -c "import sys; print(sys.path); print(sys.executable)"
    python -m pip install cryptography==2.8
  displayName: 'Demonstrate regression with pip install of cryptography'
